export const CommandClose = 'close'
export const CommandConnect = 'connect'
export const CommandDisconnect = 'disconnect'
export const CommandList = 'list'
export const CommandOpen = 'open'
export const CommandStatus = 'status'
